# Generated by Django 4.2.4 on 2023-08-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
